name: Amber
version: 1.0.0
main: com.creepercountry.amber.main.AmberPlugin
description: 'Just like towny, except works with worldguard, and doesnt have stupid features.'
author: [stealth62, AksanSai]
website: 'www.creepercountry.com'
softdepend:
  - Essentials
  - NoCheatPlus
depend:
  - Vault
  - WorldGuard
  - WorldEdit